import argparse
import csv
import math
import random
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import h5py
import numpy as np


MAX_PLOT_RECORDS = 8


@dataclass
class SpectraRecord:
    source_file: str
    record_kind: str
    target_sip_abundance_pct: float | None
    sip_label: str
    psm_id: str
    retention: str
    charge: int
    peptide: str
    precursor_mz: np.ndarray
    precursor_intensity: np.ndarray
    fragment_mz: np.ndarray
    theoretical_intensity: np.ndarray
    experimental_intensity: np.ndarray
    ion_kinds: list[str]
    ion_positions: np.ndarray
    source_index: int


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Visualize matched experimental spectra generated by "
            "openmp/experimental_spectra_main.cpp. Each plotted PSM shows the "
            "theoretical precursor envelope and a mirror plot of experimental "
            "fragment intensities against theoretical fragment intensities."
        )
    )
    parser.add_argument(
        "--input",
        default="data/spectra/spectra_C13_001.000Pct.h5",
        help="Matched experimental spectra HDF5 file, or a directory containing .h5 files.",
    )
    parser.add_argument(
        "--output",
        default="test/matched_experimental_spectra_top.pdf",
        help="Output plot path.",
    )
    parser.add_argument(
        "--tsv-output",
        default="",
        help="Output TSV path for selected peak rows. Defaults to the plot path with .tsv suffix.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=5,
        help="Number of records to select; plots at most 8.",
    )
    parser.add_argument(
        "--sample-size",
        type=int,
        default=1000,
        help="Number of records to sample before ranking. Use 0 to rank all records.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed used when sampling records.",
    )
    parser.add_argument(
        "--rank-by",
        choices=["matched-envelopes", "matched-peaks", "source-order", "random"],
        default="matched-envelopes",
        help="How selected records are ranked after sampling.",
    )
    parser.add_argument(
        "--psm-id",
        action="append",
        default=[],
        help="Plot a specific PSM id. Can be supplied multiple times; bypasses sampling/ranking.",
    )
    parser.add_argument(
        "--min-matched-envelopes",
        type=int,
        default=0,
        help="Only consider records with at least this many matched fragment envelopes.",
    )
    parser.add_argument(
        "--mz-min",
        type=float,
        default=None,
        help="Optional lower m/z bound for the fragment panel.",
    )
    parser.add_argument(
        "--mz-max",
        type=float,
        default=None,
        help="Optional upper m/z bound for the fragment panel.",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Display the figure after saving it.",
    )
    return parser.parse_args()


def _decode_hdf5_strings(values):
    decoded = []
    for value in values:
        if isinstance(value, bytes):
            decoded.append(value.decode("utf-8").rstrip("\x00"))
        else:
            decoded.append(str(value).rstrip("\x00"))
    return decoded


def _decode_hdf5_chars(values):
    chars = []
    array = np.asarray(values)
    if array.dtype.kind == "S":
        for value in array:
            chars.append(value.decode("utf-8").rstrip("\x00"))
    else:
        for value in array:
            chars.append(chr(int(value)))
    return chars


def _decode_hdf5_scalar_string(value):
    if isinstance(value, bytes):
        return value.decode("utf-8").rstrip("\x00")
    if hasattr(value, "item"):
        try:
            return _decode_hdf5_scalar_string(value.item())
        except ValueError:
            pass
    return str(value).rstrip("\x00")


def _read_hdf5_metadata(handle):
    attrs = handle.attrs
    sip_atom = _decode_hdf5_scalar_string(attrs.get("sip_atom", ""))
    sip_mass = attrs.get("sip_isotope_mass_number", None)
    if sip_mass is not None:
        try:
            sip_mass = int(sip_mass)
        except (TypeError, ValueError):
            sip_mass = 0
    else:
        sip_mass = 0
    sip_label = f"{sip_atom}{sip_mass}" if sip_atom and sip_mass > 0 else sip_atom

    abundance = attrs.get("target_sip_abundance_pct", None)
    if abundance is not None:
        try:
            abundance = float(abundance)
        except (TypeError, ValueError):
            abundance = None

    return {
        "record_kind": _decode_hdf5_scalar_string(attrs.get("record_kind", "")),
        "target_sip_abundance_pct": abundance,
        "sip_label": sip_label,
    }


def load_hdf5_records(path):
    records = []
    with h5py.File(path, "r") as handle:
        metadata = _read_hdf5_metadata(handle)
        psm_ids = _decode_hdf5_strings(handle["records/psm_id"][:])
        retentions = _decode_hdf5_strings(handle["records/retention"][:])
        charges = handle["records/charge"][:].astype(int)
        peptides = _decode_hdf5_strings(handle["records/peptide"][:])

        precursor_mz = handle["precursor/mz"][:]
        precursor_intensity = handle["precursor/intensity"][:]
        precursor_offset = handle["precursor/offset"][:].astype(np.int64)
        precursor_count = handle["precursor/count"][:].astype(np.int64)

        fragment_mz = handle["fragments/mz"][:]
        theoretical_intensity = handle["fragments/theoretical_intensity"][:]
        experimental_intensity = handle["fragments/experimental_intensity"][:]
        ion_kind = handle["fragments/ion_kind"][:]
        ion_position = handle["fragments/ion_position"][:].astype(int)
        fragment_offset = handle["fragments/offset"][:].astype(np.int64)
        fragment_count = handle["fragments/count"][:].astype(np.int64)

        n_records = len(psm_ids)
        if not (
            len(retentions)
            == len(charges)
            == len(peptides)
            == len(precursor_offset)
            == len(precursor_count)
            == len(fragment_offset)
            == len(fragment_count)
            == n_records
        ):
            raise ValueError(f"{path}: record-level dataset lengths do not match")

        for index in range(n_records):
            p_start = int(precursor_offset[index])
            p_stop = p_start + int(precursor_count[index])
            f_start = int(fragment_offset[index])
            f_stop = f_start + int(fragment_count[index])
            records.append(
                SpectraRecord(
                    source_file=path.name,
                    record_kind=metadata["record_kind"],
                    target_sip_abundance_pct=metadata["target_sip_abundance_pct"],
                    sip_label=metadata["sip_label"],
                    psm_id=psm_ids[index],
                    retention=retentions[index],
                    charge=int(charges[index]),
                    peptide=peptides[index],
                    precursor_mz=np.asarray(precursor_mz[p_start:p_stop], dtype=float),
                    precursor_intensity=np.asarray(precursor_intensity[p_start:p_stop], dtype=float),
                    fragment_mz=np.asarray(fragment_mz[f_start:f_stop], dtype=float),
                    theoretical_intensity=np.asarray(theoretical_intensity[f_start:f_stop], dtype=float),
                    experimental_intensity=np.asarray(experimental_intensity[f_start:f_stop], dtype=float),
                    ion_kinds=_decode_hdf5_chars(ion_kind[f_start:f_stop]),
                    ion_positions=np.asarray(ion_position[f_start:f_stop], dtype=int),
                    source_index=index,
                )
            )
    return records


def _input_hdf5_paths(path):
    if path.is_dir():
        files = sorted(
            item
            for item in path.iterdir()
            if item.is_file() and item.suffix.lower() in {".h5", ".hdf5"}
        )
        if not files:
            raise ValueError(f"{path}: no .h5 or .hdf5 files found")
        return files
    if path.suffix.lower() not in {".h5", ".hdf5"}:
        raise ValueError(f"{path}: expected an HDF5 spectra file or directory")
    return [path]


def load_records(path):
    records = []
    for hdf5_path in _input_hdf5_paths(path):
        records.extend(load_hdf5_records(hdf5_path))
    return records


def matched_peak_count(record):
    return int(np.count_nonzero(record.experimental_intensity > 0.0))


def envelope_keys(record):
    return list(zip(record.ion_kinds, record.ion_positions.tolist()))


def matched_envelope_count(record):
    matched = set()
    for key, intensity in zip(envelope_keys(record), record.experimental_intensity):
        if intensity > 0.0:
            matched.add(key)
    return len(matched)


def retained_envelope_count(record):
    return len(set(envelope_keys(record)))


def _sample_records(records, sample_size, seed):
    if sample_size == 0 or len(records) <= sample_size:
        return list(records)
    rng = random.Random(seed)
    return rng.sample(records, sample_size)


def _select_records(records, args):
    if args.psm_id:
        by_id = {record.psm_id: record for record in records}
        missing = [psm_id for psm_id in args.psm_id if psm_id not in by_id]
        if missing:
            raise SystemExit(f"PSM id not found: {', '.join(missing)}")
        return [by_id[psm_id] for psm_id in args.psm_id]

    filtered = [
        record
        for record in records
        if matched_envelope_count(record) >= args.min_matched_envelopes
    ]
    sampled = _sample_records(filtered, args.sample_size, args.seed)
    if args.rank_by == "random":
        rng = random.Random(args.seed)
        rng.shuffle(sampled)
        return sampled[: args.top_k]
    if args.rank_by == "source-order":
        ranked = sorted(sampled, key=lambda record: record.source_index)
    elif args.rank_by == "matched-peaks":
        ranked = sorted(
            sampled,
            key=lambda record: (matched_peak_count(record), matched_envelope_count(record), -record.source_index),
            reverse=True,
        )
    else:
        ranked = sorted(
            sampled,
            key=lambda record: (matched_envelope_count(record), matched_peak_count(record), -record.source_index),
            reverse=True,
        )
    return ranked[: args.top_k]


def _format_value(value):
    if value is None:
        return ""
    if isinstance(value, float):
        if math.isfinite(value):
            return f"{value:.10g}"
        return ""
    return str(value)


def _safe_float(text):
    try:
        value = float(text)
    except (TypeError, ValueError):
        return None
    return value if math.isfinite(value) else None


def _truncate_text(text, max_len=48):
    text = str(text or "")
    if len(text) <= max_len:
        return text
    return text[: max_len - 3] + "..."


def _plot_peak_series(ax, mz, intensity, color, label, direction=1.0, linewidth=0.5, alpha=0.72):
    if mz.size == 0:
        return
    ax.vlines(
        mz,
        0.0,
        direction * intensity,
        color=color,
        alpha=alpha,
        linewidth=linewidth,
        label=label,
    )


def _set_mz_xlim(ax, mz_values, mz_min=None, mz_max=None):
    if mz_min is not None or mz_max is not None:
        if mz_min is None:
            mz_min = float(np.min(mz_values)) if mz_values.size else 0.0
        if mz_max is None:
            mz_max = float(np.max(mz_values)) if mz_values.size else mz_min + 1.0
        ax.set_xlim(mz_min, mz_max)
        return
    if mz_values.size == 0:
        ax.set_xlim(0.0, 1.0)
        return
    min_mz = float(np.min(mz_values))
    max_mz = float(np.max(mz_values))
    if math.isclose(min_mz, max_mz):
        pad = max(1.0, 0.02 * max_mz)
    else:
        pad = max(1.0, 0.02 * (max_mz - min_mz))
    ax.set_xlim(min_mz - pad, max_mz + pad)


def _dedup_legend(ax):
    handles, labels = ax.get_legend_handles_labels()
    if not handles:
        return
    dedup = {}
    for handle, label in zip(handles, labels):
        dedup.setdefault(label, handle)
    ax.legend(dedup.values(), dedup.keys(), loc="upper right", fontsize=8)


def _plot_precursor(ax, record):
    max_intensity = float(record.precursor_intensity.max()) if record.precursor_intensity.size else 1.0
    _plot_peak_series(
        ax,
        record.precursor_mz,
        record.precursor_intensity,
        color="tab:green",
        label="Theoretical precursor",
        linewidth=1.2,
        alpha=0.85,
    )
    ax.set_ylim(0.0, max(1.05, max_intensity * 1.08))
    _set_mz_xlim(ax, record.precursor_mz)
    ax.set_xlabel("m/z")
    ax.set_ylabel("Relative intensity")
    ax.set_title("Precursor Envelope")
    _dedup_legend(ax)


def _plot_fragments(ax, record, mz_min=None, mz_max=None):
    if mz_min is None and mz_max is None:
        mask = np.ones(record.fragment_mz.shape[0], dtype=bool)
    else:
        mask = np.ones(record.fragment_mz.shape[0], dtype=bool)
        if mz_min is not None:
            mask &= record.fragment_mz >= mz_min
        if mz_max is not None:
            mask &= record.fragment_mz <= mz_max

    mz = record.fragment_mz[mask]
    theory = record.theoretical_intensity[mask]
    experiment = record.experimental_intensity[mask]
    kinds = np.asarray(record.ion_kinds, dtype=object)[mask]

    matched_mask = experiment > 0.0
    b_mask = kinds == "b"
    y_mask = kinds == "y"

    _plot_peak_series(
        ax,
        mz[matched_mask & b_mask],
        experiment[matched_mask & b_mask],
        color="tab:blue",
        label="Experimental b",
        linewidth=0.5,
    )
    _plot_peak_series(
        ax,
        mz[matched_mask & y_mask],
        experiment[matched_mask & y_mask],
        color="tab:purple",
        label="Experimental y",
        linewidth=0.5,
    )
    _plot_peak_series(
        ax,
        mz[~matched_mask],
        theory[~matched_mask],
        color="0.78",
        label="Unmatched theoretical",
        direction=-1.0,
        linewidth=0.35,
        alpha=0.55,
    )
    _plot_peak_series(
        ax,
        mz[matched_mask],
        theory[matched_mask],
        color="tab:orange",
        label="Matched theoretical",
        direction=-1.0,
        linewidth=0.4,
        alpha=0.65,
    )

    ax.axhline(0.0, color="0.5", linewidth=0.8)
    ax.set_ylim(-1.05, 1.05)
    _set_mz_xlim(ax, mz, mz_min, mz_max)
    ax.set_xlabel("m/z")
    ax.set_ylabel("Relative intensity")
    ax.set_title("Fragments: Experimental vs Theoretical")
    ax.text(0.01, 0.96, "Experimental", transform=ax.transAxes, ha="left", va="top", fontsize=8)
    ax.text(0.01, 0.04, "Theoretical", transform=ax.transAxes, ha="left", va="bottom", fontsize=8)
    _dedup_legend(ax)


def _write_selected_tsv(records, output_path):
    fieldnames = [
        "record_rank",
        "source_file",
        "record_kind",
        "sip_label",
        "target_sip_abundance_pct",
        "psm_id",
        "retention",
        "charge",
        "peptide",
        "matched_envelopes",
        "retained_envelopes",
        "matched_peaks",
        "peak_index",
        "peak_kind",
        "ion_kind",
        "ion_position",
        "mz",
        "theoretical_intensity",
        "experimental_intensity",
    ]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    row_count = 0
    with output_path.open("w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames, delimiter="\t")
        writer.writeheader()
        for record_rank, record in enumerate(records, start=1):
            base = {
                "record_rank": record_rank,
                "source_file": record.source_file,
                "record_kind": record.record_kind,
                "sip_label": record.sip_label,
                "target_sip_abundance_pct": _format_value(record.target_sip_abundance_pct),
                "psm_id": record.psm_id,
                "retention": record.retention,
                "charge": record.charge,
                "peptide": record.peptide,
                "matched_envelopes": matched_envelope_count(record),
                "retained_envelopes": retained_envelope_count(record),
                "matched_peaks": matched_peak_count(record),
            }
            for peak_index, mz in enumerate(record.precursor_mz):
                row = dict(base)
                row.update(
                    {
                        "peak_index": peak_index,
                        "peak_kind": "precursor",
                        "mz": _format_value(float(mz)),
                        "theoretical_intensity": _format_value(float(record.precursor_intensity[peak_index])),
                    }
                )
                writer.writerow(row)
                row_count += 1
            for peak_index, mz in enumerate(record.fragment_mz):
                row = dict(base)
                row.update(
                    {
                        "peak_index": peak_index,
                        "peak_kind": "fragment",
                        "ion_kind": record.ion_kinds[peak_index],
                        "ion_position": int(record.ion_positions[peak_index]),
                        "mz": _format_value(float(mz)),
                        "theoretical_intensity": _format_value(float(record.theoretical_intensity[peak_index])),
                        "experimental_intensity": _format_value(float(record.experimental_intensity[peak_index])),
                    }
                )
                writer.writerow(row)
                row_count += 1
    return row_count


def _matched_envelope_summary(records):
    if not records:
        return None
    counts = np.asarray([matched_envelope_count(record) for record in records], dtype=float)
    return {
        "min": float(np.min(counts)),
        "max": float(np.max(counts)),
        "median": float(np.median(counts)),
        "average": float(np.mean(counts)),
    }


def _plot_records(records, input_path, output_path, args):
    plotted = records[: min(MAX_PLOT_RECORDS, len(records))]
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig, axes = plt.subplots(
        len(plotted),
        2,
        figsize=(22, 5.2 * len(plotted)),
        squeeze=False,
        gridspec_kw={"width_ratios": [1.0, 2.4]},
    )
    fig.subplots_adjust(left=0.055, right=0.99, top=0.92, bottom=0.06, hspace=0.45, wspace=0.16)

    for idx, record in enumerate(plotted):
        _plot_precursor(axes[idx][0], record)
        _plot_fragments(axes[idx][1], record, args.mz_min, args.mz_max)
        rt = _safe_float(record.retention)
        rt_text = f"{rt:.4f}" if rt is not None else (record.retention or "NA")
        abundance_text = _format_value(record.target_sip_abundance_pct)
        source_text = record.source_file
        if record.record_kind or abundance_text:
            source_text += f" | {record.record_kind or 'record'}"
            if abundance_text:
                source_text += f" {record.sip_label}={abundance_text}%"
        title = (
            f"{_truncate_text(source_text, 92)}\n"
            f"{_truncate_text(record.psm_id)} | RT={rt_text} | z={record.charge} | "
            f"matched envelopes={matched_envelope_count(record)}/{retained_envelope_count(record)} | "
            f"matched peaks={matched_peak_count(record)}\n"
            f"Peptide={_truncate_text(record.peptide, 72)}"
        )
        axes[idx][0].text(0.0, 1.1, title, transform=axes[idx][0].transAxes, fontsize=10, va="bottom")

    fig.suptitle(
        f"Matched Experimental Spectra from {input_path.name} "
        f"(selected={len(records)}, plotted={len(plotted)}, rank_by={args.rank_by})",
        fontsize=16,
    )
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    if args.show:
        plt.show()
    else:
        plt.close(fig)
    return len(plotted)


def main():
    args = parse_args()
    input_path = Path(args.input).resolve()
    output_path = Path(args.output).resolve()
    tsv_output_path = Path(args.tsv_output).resolve() if args.tsv_output else output_path.with_suffix(".tsv")

    if args.top_k <= 0:
        raise SystemExit("--top-k must be positive.")
    if args.sample_size < 0:
        raise SystemExit("--sample-size must be non-negative.")
    if args.min_matched_envelopes < 0:
        raise SystemExit("--min-matched-envelopes must be non-negative.")
    if args.mz_min is not None and args.mz_max is not None and args.mz_min >= args.mz_max:
        raise SystemExit("--mz-min must be smaller than --mz-max.")
    if not input_path.exists():
        raise SystemExit(f"Input file not found: {input_path}")

    input_hdf5_paths = _input_hdf5_paths(input_path)
    records = []
    for hdf5_path in input_hdf5_paths:
        records.extend(load_hdf5_records(hdf5_path))
    if not records:
        raise SystemExit(f"No spectra records found in {input_path}")

    selected = _select_records(records, args)
    if not selected:
        raise SystemExit("No records matched the requested filters.")

    plotted_count = _plot_records(selected, input_path, output_path, args)
    tsv_row_count = _write_selected_tsv(selected, tsv_output_path)
    summary = _matched_envelope_summary(records)

    print(f"input_path={input_path}")
    print(f"input_hdf5_files={len(input_hdf5_paths)}")
    print(f"valid_records={len(records)}")
    if summary is not None:
        print(
            "matched_envelope_count_"
            f"min={_format_value(summary['min'])}\t"
            f"max={_format_value(summary['max'])}\t"
            f"median={_format_value(summary['median'])}\t"
            f"average={_format_value(summary['average'])}"
        )
    print(f"selected_records={len(selected)}")
    print(f"plotted_records={plotted_count}")
    print(f"tsv_peak_rows={tsv_row_count}")
    for record in selected[:plotted_count]:
        print(
            f"plotted_psm={record.psm_id}\t"
            f"RT={record.retention or 'NA'}\t"
            f"Charge={record.charge}\t"
            f"matched_envelopes={matched_envelope_count(record)}\t"
            f"retained_envelopes={retained_envelope_count(record)}\t"
            f"matched_peaks={matched_peak_count(record)}"
        )
    print(f"output_plot={output_path}")
    print(f"output_tsv={tsv_output_path}")


if __name__ == "__main__":
    main()
